[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:mongodb]
command=mongod --dbpath /data/db --bind_ip 127.0.0.1 --port 27017
autostart=true
autorestart=true
stdout_logfile=/var/log/mongodb/mongod.log
stderr_logfile=/var/log/mongodb/mongod_err.log
priority=1

[program:akekos]
command=node /app/app.js
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/akekos.log
stderr_logfile=/var/log/supervisor/akekos_err.log
environment=NODE_ENV="production",PORT="3027",MONGO_URI="mongodb://127.0.0.1:27017/akekos",SESSION_SECRET="akekos_session_secret_degistir"
priority=2
startsecs=5
